# -*- coding: utf-8 -*-
"""houghtransform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9QU2VORfPlW-BypNMxvAlMF2_258-x-
"""

## Developed by : HARI PRIYA M
## Reg no : 212224240047

import numpy as np
import cv2
import matplotlib.pyplot as plt

# READ THE COLOR IMAGE (original image)
img_c = cv2.imread("/content/janek-valdsalu-ra0vCZ9wABk-unsplash.jpg")
img_c = cv2.cvtColor(img_c, cv2.COLOR_BGR2RGB)

# READ THE GRAY IMAGE
gray = cv2.imread("/content/janek-valdsalu-ra0vCZ9wABk-unsplash.jpg", 0)

# Convert BGR to RGB for displaying color image
gray = cv2.GaussianBlur(gray, (3, 3), 0)

# Display original and grayscale image
plt.figure(figsize=(13, 13))
plt.subplot(1, 2, 1)
plt.imshow(img_c)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(gray, cmap='gray')
plt.title("Gray Image")
plt.axis("off")
plt.show()

# Apply Canny edge detection
canny = cv2.Canny(gray, 120, 150)

# Show canny edge image
plt.figure(figsize=(6, 6))
plt.imshow(canny, cmap='gray')
plt.title("Canny Edge Detector")
plt.axis("off")
plt.show()

# Detect lines using Hough Transform
lines = cv2.HoughLinesP(canny, 1, np.pi/180, threshold=100, minLineLength=50, maxLineGap=20)

for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(img_c, (x1, y1), (x2, y2), (255, 0, 0), 3)

# Display final result
plt.figure(figsize=(8, 8))
plt.imshow(img_c)
plt.title("Result Image - Hough Line Transform")
plt.axis("off")
plt.show()